import {
  Activity,
  AlarmClock,
  Apple,
  Bath,
  Bed,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  CalendarCheck,
  CigaretteOff,
  Code,
  Coffee,
  Droplet,
  Dumbbell,
  FaceSlightlySmiling,
  Flame,
  Flower2,
  Footprints,
  Glasses,
  GraduationCap,
  HandHeart,
  Headphones,
  HeartPulse,
  Languages,
  Laptop,
  Leaf,
  Mail,
  Moon,
  Mountain,
  Music,
  Newspaper,
  NotebookPen,
  Pencil,
  PiggyBank,
  Pill,
  Salad,
  Smartphone,
  Sparkles,
  Sprout,
  Sun,
  Target,
  Timer,
  Tv,
  Utensils,
  Wallet,
  WavesHorizontal,
  WineOff,
  type LucideIcon,
} from 'lucide-react';
import { isHabitIcon, type HabitIcon as HabitIconName } from '../domain/icons';

export const ICON_COMPONENTS: Record<HabitIconName, LucideIcon> = {
  sparkles: Sparkles,
  droplet: Droplet,
  coffee: Coffee,
  moon: Moon,
  bed: Bed,
  sun: Sun,
  'alarm-clock': AlarmClock,
  'book-open': BookOpen,
  headphones: Headphones,
  'notebook-pen': NotebookPen,
  pencil: Pencil,
  newspaper: Newspaper,
  mail: Mail,
  brain: Brain,
  'heart-pulse': HeartPulse,
  activity: Activity,
  dumbbell: Dumbbell,
  bike: Bike,
  footprints: Footprints,
  mountain: Mountain,
  'waves-horizontal': WavesHorizontal,
  apple: Apple,
  salad: Salad,
  utensils: Utensils,
  pill: Pill,
  languages: Languages,
  'graduation-cap': GraduationCap,
  glasses: Glasses,
  music: Music,
  code: Code,
  laptop: Laptop,
  briefcase: Briefcase,
  wallet: Wallet,
  'piggy-bank': PiggyBank,
  leaf: Leaf,
  sprout: Sprout,
  'flower-2': Flower2,
  'face-slightly-smiling': FaceSlightlySmiling,
  'hand-heart': HandHeart,
  smartphone: Smartphone,
  tv: Tv,
  'cigarette-off': CigaretteOff,
  'wine-off': WineOff,
  bath: Bath,
  target: Target,
  timer: Timer,
  flame: Flame,
  'calendar-check': CalendarCheck,
};

export const ICON_LABELS: Record<HabitIconName, string> = {
  sparkles: 'Scintille',
  droplet: 'Goccia',
  coffee: 'Caffè',
  moon: 'Luna',
  bed: 'Letto',
  sun: 'Sole',
  'alarm-clock': 'Sveglia',
  'book-open': 'Libro',
  headphones: 'Cuffie',
  'notebook-pen': 'Diario',
  pencil: 'Matita',
  newspaper: 'Giornale',
  mail: 'Posta',
  brain: 'Mente',
  'heart-pulse': 'Battito',
  activity: 'Attività',
  dumbbell: 'Pesi',
  bike: 'Bici',
  footprints: 'Passi',
  mountain: 'Montagna',
  'waves-horizontal': 'Onde',
  apple: 'Mela',
  salad: 'Insalata',
  utensils: 'Posate',
  pill: 'Pillola',
  languages: 'Lingue',
  'graduation-cap': 'Studio',
  glasses: 'Occhiali',
  music: 'Musica',
  code: 'Codice',
  laptop: 'Computer',
  briefcase: 'Lavoro',
  wallet: 'Portafoglio',
  'piggy-bank': 'Risparmio',
  leaf: 'Foglia',
  sprout: 'Germoglio',
  'flower-2': 'Fiore',
  'face-slightly-smiling': 'Sorriso',
  'hand-heart': 'Gentilezza',
  smartphone: 'Telefono',
  tv: 'TV',
  'cigarette-off': 'Niente fumo',
  'wine-off': 'Niente alcol',
  bath: 'Bagno',
  target: 'Obiettivo',
  timer: 'Timer',
  flame: 'Fiamma',
  'calendar-check': 'Calendario',
};

export function HabitIcon({
  name,
  size = 20,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Icon = isHabitIcon(name) ? ICON_COMPONENTS[name] : Sparkles;
  return <Icon size={size} className={className} aria-hidden />;
}
